{
 "title": "default Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total predictions made",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pred) (drunk_detector_predictions_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Predictions over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pred) (rate(drunk_detector_predictions_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Phonetypes over time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (phonetype) (increase(drunk_detector_phonetypes_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Alerts", "type": "alertlist", "gridPos": { "h": 15, "w": 6, "x": 0, "y": 5 } },
  {
   "title": "Data quality control",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "targets": [
    {
     "expr": "sum by (quality_rule) (increase(drunk_detector_data_quality_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Population Stability Index (PSI)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "drunk_detector_psi_s", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "CPU / Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"drunk-detector\"}[1m])",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"drunk-detector\"}",
     "legendFormat": "Memory usage"
    }
   ]
  }
 ]
}